### ISSUE TITLE
ENH: add action for `get_gg_data`

### ISSUE THREAD

**Issue by colinbrislawn** [bokulich-lab/RESCRIPt#124]
I'm not sure how much this is needed, but is a compliment to #123 ENH: add action for `get_unite_data`

GreenGenes is distributed from ftp://greengenes.microbio.me/greengenes_release/ with a predictable naming scheme

Downsteam, this would replace https://github.com/caporaso-lab/pretrained-feature-classifiers/blob/master/get_gg.sh#L14-L15

**Comment by nbokulich** [comment]
such an action was never added for a reason... GG has not be updated for close to a decade now, so supporting it in RESCRIPt simply is not as high of a priority as supporting other databases with more frequent release cycles, e.g., SILVA (already supported), UNITE, GTDB, etc...

My recollection from looking at file download stats a while back found that GG was not downloaded as much as some other databases, so I just see a lower juice:squeeze ratio in adding such an action. But I am not opposed.

@thermokarst @mikerobeson what do you think? Would supporting GG in RESCRIPt add value?

**Comment by colinbrislawn** [comment]
>juice:squeeze 🍋🗜️

Yep. I was looking for a simple place to start with RESCRIPt before also using the PlutoF API.

I'm avoiding the hard problem, lol. Feel free to close if unneeded

**Comment by thermokarst** [comment]
> @thermokarst @mikerobeson what do you think? Would supporting GG in RESCRIPt add value?

Hmm, probably not. The download stats are a bit inflated for GG, too, since most of the User doc tutorials use GG for its smaller size - so those classifiers get downloaded _all the time_ when building docs, etc.

**Comment by mikerobeson** [comment]
I agree with you both @thermokarst & @nbokulich. Not worth adding IMO. But it might be something for a "good first issue" tag or something. 🤷
