### ISSUE TITLE
Download RefSeq Genomes and associated Taxonomy

### ISSUE THREAD

**Issue by mikerobeson** [bokulich-lab/RESCRIPt#125]
Provide the ability for users to download RefSeq Genome Assemblies, along with their associated taxonomy. See [this forum thread](https://forum.qiime2.org/t/building-full-length-rrna-database-using-rescript/22097/6) for more details.

Some notes:

- In order to obtain the taxonomy, 
  -  we must pull the accession from the FASTA header of the given assembly. 
  -  Or parse the Taxonomy ID from the HTML / XML of the returned Assembly Record.
- Can not obtain the taxonomy based on assembly identifiers, *i.e. GCF_000213215*.
- The goal would bbe to support the following example query against the "Assembly" db, to download all Archaeal and Bacterial Genomes: `(txid2[orgn] OR txid2157[orgn]) AND "latest_refseq"[Properties]`

**Comment by misialq** [comment]
I think this can also be addressed by using the NCBI Datasets (see #96), which I started working on a while ago (https://github.com/misialq/RESCRIPt/blob/ncbi-datasets/rescript/ncbi_datasets.py) - using a taxon ID as a query one can pull all assembled genomes, together with their metadata and taxonomies (all using the Datasets API, so no need to do much additional parsing as far as I remember)... Although, it does require some new semantic types defined in https://github.com/bokulich-lab/q2-types-genomics (for storing the genome annotations).

**Comment by nbokulich** [comment]
@misialq is this PR closed by #153 ?

**Comment by misialq** [comment]
Yes, it is!
