### ISSUE TITLE
`trim-alignment` : expose multithreading

### ISSUE THREAD

**Issue by nbokulich** [bokulich-lab/RESCRIPt#127]
`mafft` has a `--threads` option that is exposed in q2-alignment's `mafft-add` action. But this is not exposed in RESCRIPt. This option should be exposed to enable multithreading. (or maybe this is intended? when adding primers to a larger alignment does multithreading offer any advantage?)

**Comment by colinbrislawn** [comment]
Testing directly with MAFFT, yes it appears that `  --addfragments` makes use of `--thread` quite well

Database: the first 1k or 10k items in SILVA_138.1_SSURef_NR99_tax_silva_full_align_trunc.fasta

Example command:

```sh
time mafft --preservecase --inputorder --thread 1 \
  --addfragments primer1.fasta \
  Silva_1k.aln.fasta \
  | gzip -c > Silva_1k_primer1_1threads.aln.fasta.gz
```

| DB size (first n seqs) | threads | real        |
|------------------------|---------|-------------|
| 1k                     |       1 | 0m 28.557s  |
| 1k                     |       4 | 0m 15.533s  |
| 10k                    |       1 | 31m 0.793s  |
| 10k                    |       4 | 10m 47.784s |
