### ISSUE TITLE
ENH: add vsearch's `-qsegout` option to RESCRIPt

### ISSUE THREAD

**Issue by mikerobeson** [bokulich-lab/RESCRIPt#136]
We've been discussing internally, for quite a while now, to be able to extract target / amplicon regions from online sequence repositories in which one or more of the PCR primers are not present or have been removed prior to that reference sequence being deposited. That is, using primers to search for and extract the target region will fail. Or better yet, to be able to extract target regions from complete genomes. Anyway, I just realized I never made an issue for this, so here it is. :-)

This, in the past, was eloquently solved by the [-qsegout](http://drive5.com/usearch/manual8.1/opt_qsegout.html) (and perhaps [-tsegout](https://drive5.com/usearch/manual8.1/opt_tsegout.html)?) command of usearch. That is, it can use actual amplicon data, or a pre-generated list of sequences, to use for searching and extracting the target amplicons from a larger reference database (i.e. GenBank, BOLD, etc...). [This](https://www.drive5.com/usearch/manual8.1/utax_user_train.html) is the exact approach I used to make reference databases for my [pig diet paper](http://dx.doi.org/10.1002/ece3.3638), and have been wanting to implement this approach ever since we started development of RESCRIPt. Now that this has been [implemented in vsearch](https://github.com/torognes/vsearch/issues/447). I think we can start planning to include this functionality. 

*Although I think we may be limited to implementing the vsearch version which now includes the `-qsegout` option, as vsearch is currently pinned within QIIME 2 due to another plugin dependency? Hopefully, that'll be resolved soon.*

**Comment by mikerobeson** [comment]
Just a short little update... I installed the latest version of vsearch (2.21.1) into my QIIME 2 test environment. I was able to run `core-diversity-metrics` and `deblur denoise-16S` w/o issue. Thus, on the surface, it appears that UniFrac and deblur may no longer be the culprits? I can try running the other deblur actions, etc... Are there are plugins / actions I should look into? Let me know.

**Comment by thermokarst** [comment]
Hey @mikerobeson - I don't think deblur specifically _pinned_ vsearch, but rather just didn't work with newer version of vsearch. A new release of deblur just landed, we're working on pulling it into the core distro, once that's set I hope we'll be able to unpin vsearch.

**Comment by mikerobeson** [comment]
Thanks for the update @thermokarst! 

If anyone is interested I am working on the relevant code for this [here](https://github.com/mikerobeson/RESCRIPt/tree/qsegout). I still need to work on testing and test code etc... When I get further along I'll submit as a PR Draft.
