### ISSUE TITLE
dep: update joblib to 1.2 with new module structure

### ISSUE THREAD

**Issue by lizgehret** [bokulich-lab/RESCRIPt#143]
`joblib` has a new version up on conda-forge that no longer contains the same module structure that's used here:

https://github.com/bokulich-lab/RESCRIPt/blob/0a7c8228764d92e6cb59892eeeeeab13baf473fc/rescript/ncbi.py#L25

It looks as though the `LokyManager` class has been removed (as well as the entire `managers` module). This will either need to be re-worked without instantiating this class, or version 1.1 of `joblib` will need to be pinned (which is the latest version that still contains the `managers` module). This would be a good temporary solution while a replacement for the instantiation of the `LokyManager` is being worked on.

**Comment by nbokulich** [comment]
thanks for spotting this @lizgehret ! I have pinned for now and we will look into a permanent fix as soon as we can...

**Comment by BenKaehler** [comment]
Thanks @lizgehret and @nbokulich, I'm happy to look at updating our usage to reflect the new structure, unless someone else gets to it first.
