### ISSUE TITLE
Use NCBI API keys in get-ncbi-data command

### ISSUE THREAD

**Issue by hemprichbennett** [bokulich-lab/RESCRIPt#145]
It could be useful when querying NCBI using rescript to be able to provide the user's [API key](https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/), to increase the number of requests per second allowed.

**Comment by mikerobeson** [comment]
Going to close this as it is clear that NCBI requests are not the rate-limiting step. At least for the purposes being used here. This was confirmed after several rounds of testing. There was no difference in overall run time when downloading marker gene data from NCBI, with or without the `api-key`.
