### ISSUE TITLE
How to train the classifier with mixed forward primers?

### ISSUE THREAD

**Issue by BirongZhang** [bokulich-lab/RESCRIPt#152]
Hi Colin,

I hope you are doing well! Thanks for sharing this useful tool!

I am analysing V1-V2 16S rRNA sequence data. I want to use **qiime feature-classifier extract-reads** to extract reads and train a classifier.
However, this data has mixed primers. I came across this one: [How to train the classifier with multiple reverse primers? ](https://forum.qiime2.org/t/how-to-train-the-classifier-with-multiple-reverse-primers/3581). Could you please help me to have a look?

```
V1-V2 MiSeq primers
Forward: These primers are mixed at a 4:1:1:1 ratio (28F-YM is the 4)
28F-YM:        GAGTTTGATYMTGGCTCAG 
28F-Borrellia: GAGTTTGATCCTGGCTTAG 
28FChloroflex: GAATTTGATCTTGGTTCAG 
28F-Bifdo:     GGGTTCGATTCTGGCTCAG


28F-YM vs 28F-Borrellia           ==   3
28F-YM vs 28FChloroflex           ==   4
28F-YM vs 28F-Bifdo               ==   4
28F-Borrellia vs 28FChloroflex    ==   4
28F-Borrellia vs 28F-Bifdo        ==   4
28FChloroflex vs 28F-Bifdo        ==   6

(19-4) differences / 19 bp length == 78.95% similar
```
Another problem is these primers are mixed at a 4:1:1:1 ratio (28F-YM is the 4)? Should I use **28F-YM & --p-identity 0.7/0.8**?

Any advices would be highly appreciated! Thanks!

Kind regards,
Birong

**Comment by nbokulich** [comment]
hello, please post all user support questions to the QIIME 2 forum. Thank you.
