### ISSUE TITLE
Authentication error with Option 2: Install within QIIME 2 environment

### ISSUE THREAD

**Issue by singhdharmesh** [bokulich-lab/RESCRIPt#160]
Hi RESCRIPt Forum, 

I am trying to install RESCRIPt within the QIIME2.2023.5 environment but I am getting a fatal authentication error (please check the .jpg file for a screenshot of the error encountered). 
I am running qiime2 on a virtual machine (Hyper V manager, Windows 10 professional). What would you suggest to overcome this error? Is there an alternative pip install command for such installation? 
![rescript error](https://github.com/bokulich-lab/RESCRIPt/assets/81809472/29774096-b94d-444c-8515-1f7fdc428816)

Best,
D_S

**Comment by nbokulich** [comment]
Hi @singhdharmesh I am closing this issue, as all user/technical support is handled on the QIIME 2 forum. Thank you for understanding.
