### ISSUE TITLE
ENH: Add option to download the corrected `214.1` GTDB database.

### ISSUE THREAD

**Issue by mikerobeson** [bokulich-lab/RESCRIPt#168]
It appears that GTDB has made some corrections to the `214` database under a new [214.1 release](https://data.gtdb.ecogenomic.org/releases/release214/214.1/). We should add this database to the list of available downloads.

**Comment by mikerobeson** [comment]
I should have a working prototype / branch that will resolve both this and #167 soon.

**Comment by nbokulich** [comment]
closed by #169
