### ISSUE TITLE
Rescript installation in q2-amplicon-2023.9

### ISSUE THREAD

**Issue by ARW-UBT** [bokulich-lab/RESCRIPt#171]
Hello, 
I was trying to install RESCRIPt in the latest q2 release (q2-amplicon-2023.9), assuming that 
`-c https://packages.qiime2.org/qiime2/2023.5/tested/` and 
`'q2-types-genomics>2023.2'`
of the installation instructions would work as well as in 2023.5. 
For some reasons, conda install did not get over the collecting stage. 

I have not seen a 'tested' section in `/qiime2/2023.9/amplicon/` or `/qiime2/2024.2/amplicon/ `, and could not adjust the conda install command accordingly. 
Should I wait until it is tested in 2024.2 and use then the upcomming q2 release? 

Best,

**Comment by nbokulich** [comment]
Hi @ARW-UBT ,
We will update the installation instructions with the new release (and RESCRIPt will be added in the next `amplicon` release next month). In the meantime you could see the changes in this pull request for instructions that should work for adding rescript to 2023.5:
#170 

For user support questions like this, please use the QIIME 2 forum in the future. Thank you!
