### ISSUE TITLE
ENH: Add the ability to fetch the latest GTDB database (v220) to `get-gtdb-data`

### ISSUE THREAD

**Issue by mikerobeson** [bokulich-lab/RESCRIPt#183]
GTDB has just released an updated version of their database [v220](https://data.gtdb.ecogenomic.org/releases/release220/220.0/). Detailed information about this release is [here](https://gtdb.ecogenomic.org/stats/r220). We should add the appropriate versions to `get_dtdb.py`, by adding to this [dictionary](https://github.com/bokulich-lab/RESCRIPt/blob/6e87cfeb239c7cfb91126a6ed5a2e64622343bde/rescript/get_gtdb.py#L25), and set the default [here](https://github.com/bokulich-lab/RESCRIPt/blob/6e87cfeb239c7cfb91126a6ed5a2e64622343bde/rescript/get_gtdb.py#L32). Then update `plugin_setup.py` [here](https://github.com/bokulich-lab/RESCRIPt/blob/6e87cfeb239c7cfb91126a6ed5a2e64622343bde/rescript/plugin_setup.py#L956) 

Sadly it looks like they changed some of the `tar.gz` files to `fna.gz`. 🤨

**Comment by nbokulich** [comment]
fixed by #184
