### ISSUE TITLE
get-ncbi-data Command Error

### ISSUE THREAD

**Issue by rachelhawrit** [bokulich-lab/RESCRIPt#185]
I am getting the following error when running the get-ncbi-data 
This occurs even if I rearrange the order of parameters and outputs, and by changing the query to be enclosed with "" instead of ''. There are no spaces in my code either.
I am trying to obtain the ncbi 16S database to be used for Blast consensus classification!

module load anaconda3
conda activate qiime2-amplicon-2024.2

qiime rescript get-ncbi-data
        --o-sequences ncbi-seq.qza \
        --o-taxonomy ncbis-tax.qza \
        --p-n-jobs 28 \
        --p-query '(16s[All Fields] AND rrna[All Fields] AND sequence[All Fields]) AND bacteria[filter]' \
        --verbose

                  There were some problems with the command:                  
 (1/2) Missing option '--o-sequences'. ("--output-dir" may also be used)
 (2/2) Missing option '--o-taxonomy'. ("--output-dir" may also be used)
/var/spool/slurm/slurmd/job8407554/slurm_script: line 13: --o-sequences: command not found

**Comment by nbokulich** [comment]
Hi @rachelhawrit ,
Thank you for using RESCRIPt. All tech support and user questions are handled on the QIIME 2 forum, not on the RESCRIPt issue tracker, so please re-post your questions on the forum and we can help you there. Thanks!
