### ISSUE TITLE
get-ncbi-genomes: custom rank information

### ISSUE THREAD

**Issue by nbokulich** [bokulich-lab/RESCRIPt#194]
As a user, I would like to occasionally customize the taxonomic rank information provided for the genomes that I download, e.g., to include domain or subkingdom or even infraclass. 

Right now, this is not possible and the retrieved ranks are the standard/bacterial ranks (a fine default).

I would like to be able to specify which ranks I want to retrieve, e.g., similar to the action `get-ncbi-data`.

**Comment by mikerobeson** [comment]
fixed by #207
