### ISSUE TITLE
SILVA 138.2 ssu-nr99 database, only 6 levels

### ISSUE THREAD

**Issue by feixiang1209** [bokulich-lab/RESCRIPt#201]
I created the qiime format qza using SILVA-138.1-ssu-nr99 around one year ago, and always used it with no issues. However, yesterday, I downloaded the new 138.2-ssu-nr99 using RESCRIPt, and it now shows an error while using qiime taxa collapse. It seems the new data base has no information of species, only to genus. Could you please advise if there is any changes in the SILVA ssu nr99 data base?

Thanks

Plugin error from taxa:

  Requested level of 7 is larger than the maximum level available in taxonomy data (6).

Debug info has been saved to /tmp/qiime2-q2cli-err-yj8xhjz8.log

**Comment by nbokulich** [comment]
Hi @feixiang1209 all technical support and user related questions for RESCRIPt should be posted to the QIIME 2 forum. We can answer your questions there. Thanks!
