### ISSUE TITLE
How can I find the installation package for RESCRIPt that is compatible with QIIME 2024.2.0?

### ISSUE THREAD

**Issue by tata831** [bokulich-lab/RESCRIPt#210]
What version of the RESCRIPt plugin is compatible with QIIME 2024.2.0? Previously, I was unaware that the QIIME 2024.2.0 version already had a compatible RESCRIPt during the initial installation, so I installed the new version of RESCRIPt using “pip install git+https://github.com/bokulich-lab/RESCRIPt.git,” which has now caused errors when running QIIME. How should I address this? How can I find the appropriate installation package or historical versions on that website? Could you provide the installation code as well?

 Is RESCRIPt 2024.2.2 compatible? However, I could not find the installation package for RESCRIPt 2024.2.2.The installation code is as follows.

Collecting git+https://github.com/bokulich-lab/RESCRIPt.git
  Cloning https://github.com/bokulich-lab/RESCRIPt.git to /tmp/pip-req-build-xpjkde_l
  Running command git clone --filter=blob:none --quiet https://github.com/bokulich-lab/RESCRIPt.git /tmp/pip-req-build-xpjkde_l
  Resolved https://github.com/bokulich-lab/RESCRIPt.git to commit 49fc648043af56dfafa41a030ac4927bab4f4a83
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: rescript
  Building wheel for rescript (setup.py) ... done
  Created wheel for rescript: filename=rescript-2025.4.0.dev0-py3-none-any.whl size=1656981 sha256=9d264c3b810f3f4581530748dc1b5e901b5816dd951638491a67bad264cc99b4
  Stored in directory: /tmp/pip-ephem-wheel-cache-uh5vg31k/wheels/a7/2f/ca/a4cfe2ac81c54ea686727a464c1029266233e0df67566e3523
Successfully built rescript
Installing collected packages: rescript
  Attempting uninstall: rescript
    Found existing installation: rescript 2024.2.2
    Uninstalling rescript-2024.2.2:
      Successfully uninstalled rescript-2024.2.2
Successfully installed rescript-2025.4.0.dev0

**Comment by nbokulich** [comment]
Hi @tata831 please post any user support questions on the QIIME 2 forum and we can help you there. Thanks!
