### ISSUE TITLE
add "FeatureData[AlignedRNASequence]" type

### ISSUE THREAD

**Issue by mikerobeson** [bokulich-lab/RESCRIPt#30]
We'll need this, if we want to allow future editing and parsing of curated alignments from [SILVA](https://www.arb-silva.de/no_cache/download/archive/release_138/Exports/), e.g. `SILVA_138_SSURef_tax_silva_full_align_trunc.fasta.gz`.
 
Importing as `FeatureData[AlignedSequence]` obviously fails.

I think we can currently import this as `FeatureData[RNASequence]`, but this might cause confusion / issues downstream when users try to manipulate t=when imported this way.

**Comment by nbokulich** [comment]
closing this issue, as this type has been added to q2-types
