### ISSUE TITLE
parallelize *-seqs methods

### ISSUE THREAD

**Issue by nbokulich** [bokulich-lab/RESCRIPt#39]
these all use skbio to iterate over sequences; splitting into chunks should enable processing in parallel.

**Comment by misialq** [comment]
I looked at three different actions, all of which are iterating over sequences: `degap-seqs`, `cull-seqs` and `orient-seqs`. I tried to evaluate whether making those run using multiprocessing would make the overall process faster: compared master version (option A) with parallelising iterating over the sequences directly (option B) and chunking sequences and parallelising those (option C; only for degap-seqs). The tests were run on 50k sequences (~300bp each), time (in seconds) to complete every action is shown.

| option | info | branch | degap | cull | orient |
| -- | -- | -- | -- | -- | -- |
| A | no parallelisation | master | 16s | 13s | 91s |
| B | 4 processes, parallel loop |  issue-39 | 21s | 11s | 95s |
| C | 4 processes, parallel chunk processing, chunk=75bp | issue-39-chunk | 95s | - | - |

Repeated on 250k sequences:

| option | info | branch | degap | cull | orient |
| -- | -- | -- | -- | -- | -- |
| A | no parallelisation | master | 87s | 70s | - |
| B | 4 processes, parallel loop |  issue-39 | 94s | 55s | - |
| C | 4 processes, parallel chunk processing, chunk=75bp | issue-39-chunk | 690s | - | - |

Seems like in the case of `degap-seqs` and `orient-seqs`, the overhead of using multiple processes is bigger than the actual amount of computation that needs to be done on a single sequence (could also see that those processes aren't really using much CPU). Same applies to splitting sequences into chunks.

Based on that, it appears that it would be beneficial to parallelise only the `cull-seqs` action. Still need to look at `evaluate-seqs`.

**Comment by misialq** [comment]
Small update regarding the `evaluate-seqs`: parallelising kmer processing can also be beneficial (see results below), hence it's also included in the PR #79.

| kmer count | master | issue-39 |
| -- | -- | -- | 
| None | 5s | 5s | 
| 2 | 46s | 31s |
| 4 | 78s | 36s |

**Comment by mikerobeson** [comment]
This is great @misialq! Do you think we might be able to squeeze more time out of `cull-seqs`, but modifying this [line](https://github.com/bokulich-lab/RESCRIPt/blob/c5ab94e7d23f569a9e76a6d30137bd06af07cd3f/rescript/screenseq.py#L24)? It basically goes through all of the possible allowed bases, when it does not need to. We can simply stop once we detect a homopolymer of the given length. Not sure how much time would actually save...

**Comment by misialq** [comment]
I'll give it a try, thanks for the suggestion @mikerobeson!

**Comment by misialq** [comment]
@mikerobeson It looks like rewriting that wouldn't really change much:  I tried to return as soon as we find first homopolymer but the measured times were indistinguishable (measured on 250k seqs containing at least 4 homopolymers).

**Comment by mikerobeson** [comment]
Thank for checking on that @misialq.
