### ISSUE TITLE
what was killed?

### ISSUE THREAD

**Issue by devonorourke** [bokulich-lab/RESCRIPt#60]
Testing a large COI dataset with `qiime rescript evaluate-fit-classifier` using an AWS instance and the job keeps crashing. Not sure why the job is failing on this command:
```
qiime rescript evaluate-fit-classifier \
  --i-sequences "$HOME"/input/boldCOI.derep.seqs.qza \
  --i-taxonomy "$HOME"/input/boldCOI.derep.tax.qza \
  --p-reads-per-batch 5000 --p-n-jobs 4 \
  --o-classifier tidybug_nBayes_classifier_seqs.qza \
  --o-observed-taxonomy tidybug_nBayes_classifier_tax.qza \
  --o-evaluation tidybug_nBayes_classifier_viz.qzv --verbose
```

The information on the screen just says: 
```
Killed
```

and the resulting .log file doesn't contain information about the stopped job:
```
Validation: 92.70s
/home/ubuntu/miniconda3/envs/rescript/lib/python3.6/site-packages/q2_feature_classifier/classifier.py:102: UserWarning: The TaxonomicClassifier artifact that results from this method was trained using scikit-learn version 0.21.2. It cannot be used with other versions of scikit-learn. (While the classifier may complete successfully, the results will be unreliable.)
  warnings.warn(warning, UserWarning)
```

I don't think it's a memory issue as this job is running on an AWS EC2 instance with over 250GB of RAM. It's possible though, as the job that's crashing was attempted while another job was running on the same machine. That other job was another RESCRIPt command:
```
qiime rescript evaluate-cross-validate \
     --i-sequences "$HOME"/input/boldCOI.derep.seqs.qza \
     --i-taxonomy "$HOME"/input/boldCOI.derep.tax.qza \
     --p-reads-per-batch 5000 --p-n-jobs 4 \
     --o-expected-taxonomy tidybug_crossval_expected_taxonomy.qza \
     --o-observed-taxonomy tidybug_crossval_observed_taxonomy.qza
```

And that job is doing fine. No crashing (though it has been running for more than 48 hours!). 

Any ideas how to track where the issues might be originating?

**Comment by mikerobeson** [comment]
Hmm... Not really sure what the issue would be. Though I do not have much experience using AWS EC2. Probably best to run one at a time, just for sanity checking purposes. If it fails again, I can try running this on our HPC.

**Comment by nbokulich** [comment]
Definitely a memory error. Looks like the job was killed (indicating out of memory error) during the classifier training step, which is very high memory with very large sets of sequences. Attempting to run both of those high-memory jobs on the same machine caused the first one to be killed. 

`evaluate-cross-validate` takes a little less memory but more time because it is splitting the reference database into smaller chunks, so that `evaluate-fit-classifier` fails on the same machine is not a huge surprise.
