### ISSUE TITLE
using of NCBI 16S taxonomy data to make sequence reference database

### ISSUE THREAD

**Issue by shakti83kumar** [bokulich-lab/RESCRIPt#65]
Hi Sirs,
I am Shakti Kumar from India, working on metagenomics data analysis. I want to use NCBI 16S (https://ftp.ncbi.nlm.nih.gov/blast/db/16S_ribosomal_RNA.tar.gz) database to make sequence reference databases. Please help me to use RESCRIPt.

**Comment by nbokulich** [comment]
Please read the [getting help](https://github.com/bokulich-lab/RESCRIPt#getting-help) section of the README, or the tutorial section, which covers NCBI data usage. Thank you.
