### ISSUE TITLE
git cloning problem

### ISSUE THREAD

**Issue by razz1618** [bokulich-lab/RESCRIPt#72]
HI,
i cannot clone the RESCRIPt.git via pip. Every time i try i get the following error-** ERROR: Command errored out with exit status 128: git clone -q https://github.com/bokulich-lab/RESCRIPt.git /tmp/pip-req-build-ryakchyf Check the logs for full command output **. Tried to run pip directly into qiime2 env as well as by creating rescript env.

**Comment by nbokulich** [comment]
Hi @razz1618 please see the installation instructions on the main README, you are not following the recommended installation.

also please read the section on getting help, we use the qiime2 forum for answering tech support questions. Thanks!
