### ISSUE TITLE
evaluate-cross-validate crashing

### ISSUE THREAD

**Issue by BenKaehler** [bokulich-lab/RESCRIPt#75]
evaluate-cross-validate seems to have a persistent issue. I have tried to run it twice now with the same result. Here are the commands:

```
$ qiime rescript get-ncbi-data --p-query '(cytochrome c oxidase subunit 1[Title] OR cytochrome c oxidase subunit I[Title] OR cytochrome oxidase subunit 1[Title] OR cytochrome oxidase subunit I[Title] OR COX1[Title] OR CO1[Title] OR COI[Title]) AND "BARCODE"[KYWD]' --o-sequences seq.qza --o-taxonomy tax.qza --verbose --p-n-jobs 5
$ qiime rescript evaluate-cross-validate --i-sequences seq.qza --i-taxonomy tax.qza --o-expected-taxonomy expected.qza --o-observed-taxonomy observed.qza --o-evaluation evaluation.qzv --p-n-jobs 12
```

I'm running it under `qiime2-2020.8`.

I get

```
Plugin error from rescript:

  A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

  The exit codes of the workers are {SIGKILL(-9)}

Debug info has been saved to /tmp/qiime2-q2cli-err-4z14w9x3.log
```

Please find the [log file](https://github.com/bokulich-lab/RESCRIPt/files/5252485/qiime2-q2cli-err-4z14w9x3.log) attached.

**Comment by nbokulich** [comment]
note the trace leads back to q2-feature-classifier... this is the same old memory error.

The COI databases tend to be very large, especially if no filtering/dereplication is performed! So you will need lots of memory, especially if setting many jobs as you have.

**Comment by BenKaehler** [comment]
Ah yes, I couldn't see the problem because it was protected by a [Someone Else's Problem Field](https://hitchhikers.fandom.com/wiki/Somebody_Else%27s_Problem_Field).

I reduced the number of jobs to 4, which reduced the memory footprint to a much more manageable 53 GB-ish, and it hasn't crashed yet. It is going to run for a long time, though.
