### ISSUE TITLE
Silva 138 Classifier generated using RESCRIPt is not classifying Salmonella at genus level

### ISSUE THREAD

**Issue by drashutosh** [bokulich-lab/RESCRIPt#80]
Hi 
I have tried all possible versions of Silva 138 V3-V4 classifiers generated using three different dereplicating  mode "uniq" "majority" and "super" in RESCRIPt  to classify 16s sequences for mock bacterial communities from Zymoresearch https://files.zymoresearch.com/datasheets/ds1706_zymobiomics_microbial_community_standards_data_sheet.pdf
However, using these classifier are not assigning "Salmonella" at genera level which is expected to be in the community. I blasted Not_assigned ASVs to NCBI nucleotide database then I found majority of "Not_assigned" have hits with salmonella genus. 

In contrast, when I classify the same sequences with Silva 132 V3-V4 classifier, it gives me "Salmonella" at genera level.
I also classify some other sequences from other studies too, however, in every case I am missing salmonella.,  
The overall classification with Silva 138 classifier is better than Silva 132; but why I am missing salmonella, which is a bit weird for me.

Can you please give me a clue regarding this issue?

Thanks in advanced
Ashutosh

**Comment by nbokulich** [comment]
Hello @drashutosh as mentioned in the readme page, user support questions should be directed to the QIIME 2 forum.

Thank you for using RESCRIPt.
