### ISSUE TITLE
Update `get-silva-data` for downloading SILVA 138.1 LSU data

### ISSUE THREAD

**Issue by mikerobeson** [bokulich-lab/RESCRIPt#97]
The SILVA 138.1 LSU files are available [here](https://www.arb-silva.de/no_cache/download/archive/release_138.1/Exports/). This was brought to our attention in the [QIIME 2 forum](https://forum.qiime2.org/t/weird-taxonomic-classification-28s-rrna/18469/7)

**Comment by nbokulich** [comment]
fixed in #99
